import {
  Accessibility,
  Armchair,
  BadgeHelp,
  BatteryLow,
  BookOpen,
  ClipboardPlus,
  ContactRound,
  Flame,
  Frown,
  GlassWater,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  Leaf,
  Meh,
  MonitorPlay,
  MoonStar,
  Music2,
  NotebookTabs,
  PanelsTopLeft,
  PersonStanding,
  Puzzle,
  RefreshCcw,
  Shapes,
  ShieldAlert,
  Smile,
  Snowflake,
  Soup,
  Stethoscope,
  Sun,
  Trees,
  UserRound,
  Users,
  UsersRound,
  type LucideIcon
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  Accessibility,
  Armchair,
  BadgeHelp,
  BatteryLow,
  BookOpen,
  ClipboardPlus,
  ContactRound,
  Flame,
  Frown,
  GlassWater,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  Leaf,
  Meh,
  MonitorPlay,
  MoonStar,
  Music2,
  NotebookTabs,
  PanelsTopLeft,
  PersonStanding,
  Puzzle,
  RefreshCcw,
  Shapes,
  ShieldAlert,
  Smile,
  Snowflake,
  Soup,
  Stethoscope,
  Sun,
  Trees,
  UserRound,
  Users,
  UsersRound
};

export function IconSymbol({ name, size = 36, strokeWidth = 2 }: { name: string; size?: number; strokeWidth?: number }) {
  const Icon = icons[name] ?? Shapes;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
